config/routes.rb
Rails.application.routes.draw do

  root "listings#index"
  
  resources :listings, except: [:update, :edit] do
    member do
      get "description"
    end
  end

  resources :companies
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :name, :information, :location, presence: true
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates :role, :company, :location, :description, presence: true

  # Finds listings that are up to 14 days old from created
	def self.query_non_expired
		where("created_at >= ?", 2.week.ago.utc)
	end

  # Finds listings that are created on a certain date
	def self.find_by_date(date)
		where(created_at: date.beginning_of_day..date.end_of_day )
	end

  # Displays date in a readable format
	def create_date
		created_at.to_date
	end

  # Displays date in a human readable format
	def create_date_month_day
		created_at.to_date.to_formatted_s(:short)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def index
		@companies = Company.all
	end

	def show
		@company = Company.find(params[:id])
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		if @company.save
			redirect_to @company
		else
			render :new
		end
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		if @company.update(company_params)
			redirect_to @company
		else
			render :edit
		end
	end

	def destroy
		@company = Company.find(params[:id])
		@company.destroy
		redirect_to companies_path, notice: "Company was successfully deleted"
	end

	private

	def company_params
		params.require(:company).permit(:name, :information, :location, :website)
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	def index
		@listings = Listing.query_non_expired
		@listings_today = @listings.find_by_date(Time.now.utc.to_date)
		@listings_yesterday = @listings.find_by_date(Time.now.utc.to_date.yesterday)
	end

	def show
		@listing = Listing.find(params[:id])

		respond_to do |format|
			format.html { }
		end
	end

	def new
		@listing = Listing.new
		@companies = Company.all
	end

	def create
		@listing = Listing.new(listing_params)
		if @listing.save
			redirect_to @listing
		else
			render :new
		end
	end

	def description
		@listing = Listing.find(params[:id])
		respond_to do |format|
			format.html {}
			format.js { render "description" }
		end
	end

  private

	def listing_params
		params.require(:listing).permit(:role, :company, :location, :description, :company_information, :company_website)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :information %>
  <%= f.text_area :information %>
  <br>
  <%= f.label :website %>
  <%= f.text_field :website %>
  <br>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <%= f.submit :Submit %>
<% end %>

app/views/companies/edit.html.erb
<%= button_to "Delete", company_path(@company), method: :delete %>
<%= render 'form' %>

app/views/companies/index.html.erb
<% @companies.all do |company| %>
  <%= company.name %>
  <br>
  <%= company.information %>
  <br>
  <%= company.location %>
<% end %>

app/views/companies/new.html.erb
<%= render 'form' %>

app/views/companies/show.html.erb
<%= @company.name %>
<br>
<%= @company.information %>
<br>
<%= @company.location %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobsearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Project name</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

<% flash.each do |msg| %>
  <%= msg %>
<% end %>

<%= yield %>

</body>
</html>

app/views/listings/_description.html.erb
<%= listing.description %>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <%= f.label :role %>
  <%= f.text_field :role %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :company %>
  <%= f.text_field :company %>

  <%= f.label :company_information %>
  <%= f.text_area :company_information %>

  <%= f.label :company_website %>
  <%= f.text_field :company_website %>

  <%= f.submit :Submit %>
<% end %>

app/views/listings/_listing.html.erb
<div class="listing-row" data-id="<%= listing.id %>">
	<%= link_to listing.role, listing %>
	<% if listing.company_website %>
	  <%= link_to "(#{listing.company})", listing.company_website, class: "companyWebsiteLink", id: "#{listing.id}-websiteLink" %>
	<% else %>
	  <%= "(#{listing.company})" %>
	<% end %>
	<br>
	<%= "#{listing.location} - #{listing.create_date_month_day}"  %>
	<br>
	<%= button_tag "+ Description", id: "#{listing.id}-description-button", class: "show-description btn btn-primary", data_loading_text: "Loading..."%>
	</br>
</div>

app/views/listings/_listing_row.html.erb
<div data-id="<%= listing.id %>">
	<%= link_to listing.role, listing %>
	<%= "(#{listing.company})" %>
	<br>
	<%= "#{listing.location} - #{listing.create_date_month_day}"  %>
	<br>
	<p class="description">Description</p>
	</br>
</div>

app/views/listings/description.html.erb
<%= render 'description', listing: @listing %>

app/views/listings/index.html.erb
<% @listings.each do |listing| %>
  <%= render 'listing', listing: listing %>
<% end %>

app/views/listings/new.html.erb
<% @companies.each do |company| %>
  <%= button_tag company.name, class: "companyFill", data: {name: company.name, information: company.information, location: company.location, website: company.website } %>
<% end %>
<%= render 'form' %>

app/views/listings/show.html.erb
<%= @listing.role %>
<br>
<%= @listing.company %>
<br>
<%= @listing.location %>
<br>
<%= @listing.create_date %>
<br>
<%= @listing.description %>
<br>
<%= @listing.company_information %>
<br>
<%= link_to @listing.company_website, @listing.company_website %>
<br>